### ISSUE TITLE
ARM / Raspberry errors: channels-redis and python on installation of Funkwhale 0.20.1

### ISSUE THREAD

**Issue by ELCourtez** [YunoHost-Apps/funkwhale_ynh#89] opened 2019-11-04 17:03 UTC
Hi,

I have this error on installation of Funkwhale V 0.20.1 on my Yunohost instance :
`ERROR: Package 'channels-redis' requires a different Python: 3.5.3 not in '>=3.6'`

I saw the pull request #80 was supposed to correct this issue but it seems the error is still reproductible.

Here is a full log :https://paste.yunohost.org/raw/icovotidas

**Comment by Jibec** [comment] 2019-11-04 19:57
reproductible, but unfortunately not with my equipement :( Is it x86, x86_64 or arm?

**Comment by MyNameIsTroll** [comment] 2019-11-04 22:25
Same ERROR here.
On my Raspberry Pi 3 (ARM)

**Comment by ELCourtez** [comment] 2019-11-05 09:17
Hi,

I'm on a Rpi3 too so ARM :

`> _cat /proc/cpuinfo_
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
`

**Comment by BienOuBien** [comment] 2019-11-22 12:40
Hieveryone, 
The update didn't go well on my Raspberry Pi, I had the same error as you.
Now it's impossible to play my music, I don't have any album covers for you anymore. 
When I press play, this error message appears on the player: 

> The track cannot be loaded
> Il se peut que vous ayez des problèmes de connexion.

Here are my [logs](https://paste.yunohost.org/ahiqafedav.bash)


I tried to restore the backup but I still have the same problem:/

**Comment by Jibec** [comment] 2019-11-22 15:00
Because of PIP dependencies, this new version doesn't work with ARM.

I don't see what I can do, revert the release isn't possible.
Everything will should be fixed once YunoHost migrates on Buster.

What happens today: a user won't be able to update.

What we can do is to find out why your backup did not work. Please open 
a new issue, I'll answer it there.

**Comment by Sporiff** [comment] 2020-05-18 21:40
Theoretically this has been fixed in #105 as it includes an [upstream fix](https://dev.funkwhale.audio/funkwhale/funkwhale/-/commit/20f5416bd37a8ca388bd9bc73e208338d37d5f1b) to the package in question. I'll keep an eye on the build and would appreciate any feedback from Pi owners :smile:

**Comment by ELCourtez** [comment] 2020-05-19 08:52
Hi,

Tested on a fresh install of Yunohost on RPi3 :
- Funkwhale installation (v0.21) --> OK
- Upload and play some tracks --> OK

Thanks :)

**Comment by Sporiff** [comment] 2020-05-19 08:55
Thanks for the confirmation @ELCourtez. Can I just ask: did you perform the installation through the web portal or on the command line?

**Comment by ELCourtez** [comment] 2020-05-19 09:05
I performed the installation through the portal, do you want me to make another test using command lines ?

**Comment by Sporiff** [comment] 2020-05-19 09:07
> I performed the installation through the portal, do you want me to make another test using command lines ?

No, that's fine. Just interesting to know (I'm having some trouble with installing through the portal at the moment, so it's interesting but good that it's working for you)

**Comment by MyNameIsTroll** [comment] 2020-05-19 19:53
Hello,
I can confirm that it worked for me as well.
I just installed Funkwhale (v0.21) from the YunoHost web interface (v3.7.1.3 stable) it went well.
- I started uploading music (it works).
- Listening also works.

Thank you very much for your work, it's great.

**Closed** 2022-10-03 22:28 UTC
