### ISSUE TITLE
Subsonic API

### ISSUE THREAD

**Issue by rushsteve1** [YunoHost-Apps/funkwhale_ynh#44] opened 2018-10-25 22:04 UTC
The Funkwhale Subsonic API is not reachable when hosted on YunoHost. Opening port 4040, the default Subsonic port, in the firewall did nothing.

**Comment by op3nus3r** [comment] 2018-10-26 20:30
I tried to connect to my instance using the subsonic API password, it didn't work. 
I checked the box "navigate by tags".

I can still connect to other instances.

**Comment by EliotBerriot** [comment] 2018-10-27 09:52
The Subsonic API should not require any port opening and is served under the `/rest/` path. The `/rest/` path itself is not a valid route, but you can try `/rest/ping.view` (example on the demo server: https://demo.funkwhale.audio/rest/ping.view)

Maybe the issue is coming from this line: https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/conf/nginx.conf#L90

This is what we have in the official template: https://code.eliotberriot.com/funkwhale/funkwhale/blob/develop/deploy/nginx.template#L68

It looks like you have an extra "/code/" in the path :)

**Comment by Jibec** [comment] 2018-10-27 12:30
fixed by https://github.com/YunoHost-Apps/funkwhale_ynh/pull/46

thanks for reporting and helping!

**Closed by Jibec** 2018-10-27 12:30 UTC
