### ISSUE TITLE
Data folder should be in yunohost.app

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#15] opened 2018-06-19 11:04 UTC
The data folder should be in /home/yunohost.app/funkwhale/data because sometimes the media can take lot of space fill up the limited space in /var. /home folder is generally reserved with lot of space to keep all the media. Further its good idea to keep media away from the app core files.
 I have faced this issue in Peertube too. 
See here https://github.com/YunoHost-Apps/peertube_ynh/issues/8

**Comment by Jibec** [comment] 2018-06-19 21:04
I think this issue is also related to the "music" folder of #16 
One hint can be the yunohost.multimedia package: https://github.com/YunoHost-Apps/yunohost.multimedia

**Comment by rushsteve1** [comment] 2018-10-08 16:12
YunoHost also has per-user and shared media storage which should be integrated.
You can see it easily if you install Nextcloud and check off the access home option.

**Comment by Jibec** [comment] 2018-10-20 20:47
@EliotBerriot can we have one folder per user so we can enable this? https://docs.funkwhale.audio/configuration.html#music-directory-path

**Comment by EliotBerriot** [comment] 2018-10-21 13:52
Do you mean per-funkwhale user? No, it's not possible because uploaded files won't be binded to only one user anymore in the next releases, when we have deduplication in place (the same file may be uploaded by X user, but will only be stored once)

**Comment by anmol26s** [comment] 2018-10-25 14:07
But we have a media folder in yunohost that have songs folder which is shared to all the users. User can put the songs in this folder from nextcloud and it is shared to with all other users.
But anyways we should have songs directory in /home/yuohost.app/funkwhale and it should not be backedup while upgrade.

**Comment by Jibec** [comment] 2018-10-25 15:36
There is no backup of media for upgrade.
I don't see the point of multimedia for handling funkwhale's media.

So, the last use case is to provide an easy way to import files? Correct?
-- 
Jean-Baptiste Holcroft

**Comment by rushsteve1** [comment] 2018-10-25 15:40
It's more standard for YunoHost applications. And being able to easily manage/download the files themselves is quite useful.

Personally being able to use my existing Nextcloud setup to sync my music into the media folder, both to and from Funkwhale, would be very useful.

**Comment by Jibec** [comment] 2018-10-25 16:32
OK then. I'll close this request.
Ynh is for casual users and not about advanced use cases as you describe it.
Let's keep thing simple.

If you need easy download, ask the feature upstream.
If you want fast upload and you have a slow connexion, host your server on your network. If you have a fast bandwidth, it won't change anything.

**Comment by IsidoreIsou** [comment] 2019-04-16 18:50
Hello,
On my YNH server, my `/` folder is almost full, since all my music imported in FW is in it.
I'm not sure what is the best way to resolve it, so I can add more music and free this space? (this is making a lot of problem on the server)
* Enlarging the space on the `/`folder
* Moving the FW music folder
I would love to keep things as simple as possible. 
Now I have only a 2TB HDD on a VPS to have to most straightforward config possible.
![](https://framapic.org/i6oHZ16waGRO/od52cj4cdXVO)

Thanks a lot

**Comment by maniackcrudelis** [comment] 2019-04-17 15:43
As said by @anmol26s, YunoHost provides a media folder, `/home/yunohost.multimedia` design to store all media files for all apps.
As funkwhale deals with a library of audio files, those files should be stored in this directory, so it would be available for nextcloud, ampache or any other apps that would deal with audio files.
Using a dedicated directory for this app means users would have to duplicate their files to have them available from another app.

Helpers are available to use this directory painlessly.
https://github.com/YunoHost/yunohost/blob/add_ynh_multimedia_helpers/data/helpers.d/multimedia

**Comment by IsidoreIsou** [comment] 2019-04-26 16:44
For a temporary fix, moving the folder in `/home` and creating a sym link works perfectly.

**Comment by ImaCrea** [comment] 2019-09-02 22:14
cc @EliotBerriot I think we need help please 🙏
We'd love to start using it at MailTape collective to share our music discoveries between members but I'm afraid to install it atm. Could this be fixed please please :)

**Comment by EliotBerriot** [comment] 2019-09-03 10:27
Hi @ImaCrea, I'm not sure how I can help here.

The directory for uploaded  files can already be customized on Funkwhale's side (via the `MEDIA_ROOT` and `MUSIC_DIRECTORY_PATH` environment variables), I think it's YunoHost and/or funkwhale_ynh responsibility to set those paths to the best possible options depending of how a YunoHost installation is partitionned / configured, or to make this customizable maybe? (I'm not sure if this is supported in YNH though).

As I'm not a YunoHost user, developper or packager, I cannot work on this myself. Of course, I'm here to help if the person implementing this need advice regarding those variables and their use, reviewing, feedback, or anything else where my input could be useful :)

**Comment by ImaCrea** [comment] 2019-09-08 11:10
Thank you for your dear help @EliotBerriot :) @Jibec does Eliot answer help you?

**Comment by Jibec** [comment] 2019-09-08 12:36
I guess I'll do the change, too many people argue about it.
Only time is an issue.
PR are welcome.
Otherwise, it will probably take some time, because I have very few time for contribution. I'm fine with letting the project to a new maintainer if someone is willing to.

**Comment by ImaCrea** [comment] 2019-09-08 13:06
I wish I could but I'm afraid I'm lacking some tech knowledge atm to carry it :/

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Sporiff** [comment] 2020-05-20 01:15
My thoughts on this are as follows, based on this thread (I welcome feedback. I'm very new to Yunohost):

## New Installations

New installations should have their directory set to `/home/yunohost.multimedia/share/funkwhale/[media/import]` (or something similar) by default. We can achieve this by using the `.env` file to set Funkwhale to use the location by default, replacing the relevant sections in the file at install and creating the directory/setting access using the `multimedia` helper.

## Existing Installations

Existing installs will be trickier given that people may have set their servers up differently, but I would guess that the people who have manually changed their setup will be comfortable with making changes to match this repository. If we're working with the assumption that people generally leave these files in `/var/www/funkwhale/[media/import]` we can do one of the following:

* Check if the `/home/yunohost.multimedia` folder exists and create necessary subfolders
* Migrate the `media` and `import` folders to this location
* Perform the upgrade as normal with the `.env` file changed to match the new location

The problem with this approach is that Funkwhale uses the `.env` to determine where it is looking for files when it performs its database migrations, so you would need to move them before this is done which will lead to doubling up as far as I can tell (leaving files in the backup to be restored to `/var/www/funkwhale` and also in `/home/yunohost.multimedia`. The other approach is:

* Check if the `/home/yunohost.multimedia/share/funkwhale` folder exists and create necessary subfolders
* If the folder exists already, set the `.env` variables to this location. If not, proceed as normal
* If the folder does not currently exist, perform the migration as normal in the standard location and then use the `multimedia` helper to perform the necessary symlinking, leaving all files in `/home/yunohost.multimedia` but having Funkwhale continue to interact with `/var/www/funkwhale`
* When the next upgrade is run, the symlinks will be removed and everything will work as if it were a new installation with the proper `.env` variables

This second approach is more long-winded, but it is a bit more robust as far as I can tell for ensuring that we don't bork existing installations since it will work for both locations.

As I say, I welcome feedback. I'm still learning the ropes here, so it would be good to get an idea of how others would go about this.

**Comment by jmbmkn** [comment] 2020-09-01 17:00
> My thoughts on this are as follows, based on this thread (I welcome feedback. I'm very new to Yunohost):
> ## New Installations
> 
> New installations should have their directory set to `/home/yunohost.multimedia/share/funkwhale/[media/import]` (or something similar) by default. We can achieve this by using the `.env` file to set Funkwhale to use the location by default, replacing the relevant sections in the file at install and creating the directory/setting access using the `multimedia` helper.
> ## Existing Installations
> 
> Existing installs will be trickier given that people may have set their servers up differently, but I would guess that the people who have manually changed their setup will be comfortable with making changes to match this repository. If we're working with the assumption that people generally leave these files in `/var/www/funkwhale/[media/import]` we can do one of the following:
> 
>     * Check if the `/home/yunohost.multimedia` folder exists and create necessary subfolders
> 
>     * Migrate the `media` and `import` folders to this location
> 
>     * Perform the upgrade as normal with the `.env` file changed to match the new location
> 
> 
> The problem with this approach is that Funkwhale uses the `.env` to determine where it is looking for files when it performs its database migrations, so you would need to move them before this is done which will lead to doubling up as far as I can tell (leaving files in the backup to be restored to `/var/www/funkwhale` and also in `/home/yunohost.multimedia`. The other approach is:
> 
>     * Check if the `/home/yunohost.multimedia/share/funkwhale` folder exists and create necessary subfolders
> 
>     * If the folder exists already, set the `.env` variables to this location. If not, proceed as normal
> 
>     * If the folder does not currently exist, perform the migration as normal in the standard location and then use the `multimedia` helper to perform the necessary symlinking, leaving all files in `/home/yunohost.multimedia` but having Funkwhale continue to interact with `/var/www/funkwhale`
> 
>     * When the next upgrade is run, the symlinks will be removed and everything will work as if it were a new installation with the proper `.env` variables
> 
> 
> This second approach is more long-winded, but it is a bit more robust as far as I can tell for ensuring that we don't bork existing installations since it will work for both locations.
> 
> As I say, I welcome feedback. I'm still learning the ropes here, so it would be good to get an idea of how others would go about this. I'm also curious about what expectations are with regards to deinstallation. Should files remain where they are?

Can I reproduce this on a fresh installation of Funkwhale? Do I just change the env var 'MEDIA_ROOT=' to '`/home/yunohost.multimedia/share/funkwhale/' and it will just work, or do I need to do an in place import?

**Closed** 2021-04-24 11:05 UTC
Labels: help wanted
