### ISSUE TITLE
Log in does not worked

### ISSUE THREAD

**Issue by llinfrance** [YunoHost-Apps/funkwhale_ynh#25] opened 2018-07-10 20:01 UTC
Hi,

I tried my best, but I am still not able to log in ! I am sure the username/password is correct. I am able to log in to the admin section.
In the admin section, I create a new user but with the same issue : after clicking on log in, it goes quickly into the empty library, but it switch back straight to the log in page.

Could you tell me where to to look ? Like were are the log files ?
Cheers

**Comment by Jibec** [comment] 2018-07-24 11:33
Hi, can you please explain what do you mean by "I am able to log in to the admin section." ?

**Comment by anmol26s** [comment] 2018-07-24 12:29
I think @llinfrance means the Django interface i.e. /api/admin.  
@llinfrance You have to use the same username which you had given at the time of installation and password is funkwhale. I hope you are not getting confused with this. If this don't work please clear your cache and try again.

**Comment by llinfrance** [comment] 2018-07-25 17:53
Thank you for your answers.

@anmol26s is right : I meant that I was able to log in the Django interface, which also means that the username/password are corrects.

Moreover, I already tried clearing the cache.

Do you know where should I looked to read any error messages ?

**Comment by Jibec** [comment] 2018-08-02 20:07
@EliotBerriot can you help?

**Comment by PierrickBrun** [comment] 2018-08-22 11:08
As you can see the login answered with a 200 but then the following calls answer with a 401.
On login the token is well received ({token: xxx})

This is on firefox.

![ksnip_20180822](https://user-images.githubusercontent.com/8819682/44460136-4e672100-a60c-11e8-9ad3-643f5cf47afa.png)

**Comment by EliotBerriot** [comment] 2018-08-22 13:56
@PierrickBrun do you use any kind of plugin in your web browser that could mess with localstorage? Do you reproduce the issue in other browsers or when disabling your browser extensions?

**Comment by llinfrance** [comment] 2018-09-01 11:31
Hello guys, sorry for my long silence...

I did as @PierrickBrun  mentionned, and it works partially. Clicking on "forget about this website" allowed me to log in ! Sometimes, I had to do it again as I am logged out after browsing somewhere in my funkwhale instance. (Firefox)

I try also with extensions disable, but it was the same. I have to "forget about this website". (Firefox)

I try also with Safari. It works. And then, I realized that the Administration showing in the left panel present in Safari was not present at all on Firefox ! I have no idea if this is related somehow.

**Comment by llinfrance** [comment] 2018-09-01 11:46
It is me again, I just realized something : when I am logged in on my yunohost account, I am logged out on my funkwhale instance and vice et versa ! 
It might be a clue ?

**Comment by PierrickBrun** [comment] 2018-09-02 10:05
Sorry I didn't have a chance to test again with a browser without add-ons (I need to be logged-in for a while on it before it happens).

What @llinfrance mentions about yunohost log-out is interesting, I use the same username on yunohost and funkwhale and that may be the cause of my problem too.
Also I think resolving #21 (and https://code.eliotberriot.com/funkwhale/funkwhale/issues/335) would correct it. Maybe we shouldn't waste time on this issue since the LDAP support is already planned and will handle it ?

**Comment by fflorent** [comment] 2018-10-07 18:37
Version 0.17.0 is out now with the LDAP authentication: https://code.eliotberriot.com/funkwhale/funkwhale/commit/510844f31cc85fe9d2e43a47ed6322735743590e

**Comment by rushsteve1** [comment] 2018-10-08 16:10
The testing branch is on 0.17 which has LDAP.
And the PR I just made #37 bumps it to the released version and turns LDAP on. Still needs work but it's there.

**Comment by Jibec** [comment] 2018-10-20 20:31
Should work in the future: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/3e44180708dddbef360e25841b9cf7be6e144c95

**Closed by Jibec** 2018-10-20 20:31 UTC

**Comment by PierrickBrun** [comment] 2018-10-27 16:02
For the sake of good order, I confirm this is fixed with the 0.17 update and LDAP support
