### ISSUE TITLE
Problem with the funkwhale-worker service

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/funkwhale_ynh#3] opened 2018-05-12 13:04 UTC
Hello

I have tried to install you app but the funkwhale-worker service don't start

The logs of the service:

https://framabin.org/?04399e59ecbd3615#07pLBdiFxsFcruiBO4MFmenck4mjqR+QiP2rLPnUP8c=

**Comment by Jibec** [comment] 2018-05-12 14:08
Hello, thanks for your report, can you please describe the hardware you're using? Did you try with the latest funkwhale source code? I update community.json today.
-- 
Jean-Baptiste Holcroft

**Comment by Rafi594** [comment] 2018-05-12 14:41
I'm using 64bits server and I have installed funkwhale with sudo yunohost app install https://github.com/YunoHost-Apps/funkwhale_ynh

**Comment by EliotBerriot** [comment] 2018-05-12 15:33
This looks like a layout or path issue. @Rafi594, can you please share the layout of your `/var/www/funkwhale`directory (for example using `tree /var/www/funkwhale`) ?

**Comment by Rafi594** [comment] 2018-05-12 15:51
I can't use tree because the result is too long
```
/var/www/funkwhale $ ls
api  CHANGELOG  changes  config  CONTRIBUTING  CONTRIBUTORS.txt  data  demo  deploy  dev.yml  docker  docs  front  LICENSE  load_env  po  pyproject.toml  README.rst  virtualenv

```
```
/var/www/funkwhale/virtualenv $ ls
bin  etc  include  lib  lib64  pip-selfcheck.json  pyvenv.cfg  share
```

The end of the tree command
https://paste.yunohost.org/sokozivego.css

**Comment by Jibec** [comment] 2018-05-12 19:39
so, the issue is coming from redis, commenting CACHE_URL in .env, and running `systemctl restart funkwhale.target` disables it

**Comment by Jibec** [comment] 2018-05-12 21:59
Should be fixed by: https://github.com/YunoHost-Apps/funkwhale_ynh/pull/4
please re-open if needed

**Closed by Jibec** 2018-05-12 21:59 UTC
